name: Deploy
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop app || true
            docker rm app || true
            docker pull cr.yandex/<registry_id>/app:${{ github.event.inputs.version }}_latest
            docker run -d --name app -p 80:3000 -p 443:3000 cr.yandex/<registry_id>/app:${{ github.event.inputs.version }}_latest
